apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    name: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc2
      containers:
      - name: node
        image: gcr.io/clo-comp-two/node-kubernetes:latest # upda
        volumeMounts:
        - name: nfs-volume
          mountPath: /tmp
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
        livenessProbe:
            httpGet:
                path: /healthz
                port: 3000
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
      
